name: CI

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'tests/**'
      - 'yarn.lock'
      - '.github/workflows/main.yml'
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'
      - 'yarn.lock'
      - '.github/workflows/main.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: bahmutov/npm-install@v1